MVC_Camp/Controllers/AdminCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace MVC_Camp.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        public ActionResult Index()
        {
            var categoryValues = cm.GetList();
            return View(categoryValues);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);

            if (results.IsValid)
            {
                cm.CategoryAddBl(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var category = cm.GetById(id);
            cm.CategoryDelete(category);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryValue = cm.GetById(id);
            return View(categoryValue);
        }

        [HttpPost]
        public ActionResult EditCategory(Category category)
        {
            cm.CategoryUpdate(category);
            return RedirectToAction("Index");
        }
    }
}

MVC_Camp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace MVC_Camp.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCategoryList()
        {
            var categoryValues = cm.GetList();
            return View(categoryValues);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);

            if (results.IsValid)
            {
                cm.CategoryAddBl(p);
                return RedirectToAction("GetCategoryList");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();
        }
    }
}

MVC_Camp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Camp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC_Camp/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Concrete;

namespace MVC_Camp.Controllers
{
    public class StatisticsController : Controller
    {
        Context context = new Context();

        public ActionResult Index()
        {
            var totalCategories = context.Categories.Count();
            Console.WriteLine(totalCategories);
            var headingsInDevelopment = context.Headings.Count(x => x.CategoryId == 8);
            var aInWriterName = context.Writers.Count(x => x.WriterName.Contains("a"));
            var mostHeadingsCategory = context.Categories.Where(u => u.CategoryId == context.Headings.GroupBy(x => x.CategoryId).OrderByDescending(x => x.Count()).Select(x => x.Key).FirstOrDefault()).Select(x => x.CategoryName).FirstOrDefault();
            var activeCategories = context.Categories.Count(x => x.CategoryStatus == true);
            var passiveCategories = context.Categories.Count(x => x.CategoryStatus == false);

            ViewBag.totalCategories = totalCategories;
            ViewBag.headingsInDevelopment = headingsInDevelopment;
            ViewBag.aInWriterName = aInWriterName;
            ViewBag.mostHeadingsCategory = mostHeadingsCategory;
            if (activeCategories > passiveCategories)
            {
                ViewBag.totalCategory = activeCategories - passiveCategories;
                ViewBag.messageForcategories = "There are more active Categories.";
            }
            else
            {
                ViewBag.totalCategory = passiveCategories - activeCategories;
                ViewBag.messageForcategories = "There are more passive Categories.";
            }

            return View();
        }
    }
}

MVC_Camp/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h1>Add New Category Page</h1>
<br />

@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Category Name:")
        @Html.TextBoxFor(x => x.CategoryName, new {@class="form-control"})
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Enter the description:")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /><br />
        <button class="btn btn-success">Save</button>
    </div>
}

MVC_Camp/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category


@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Category Updating Page</h2>

@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Category ID")
        @Html.TextBoxFor(x=>x.CategoryId, new { @class = "form-control" })
        <br/>
        @Html.Label("Category Name")
        @Html.TextBoxFor(x=>x.CategoryName, new { @class = "form-control" })
        <br/>
        @Html.Label("Category Description")
        @Html.TextAreaFor(x=>x.CategoryDescription, new { @class = "form-control" })
        <br/>
        @*@Html.Label("Category Status")
        @Html.TextBoxFor(x=>x.CategoryStatus, new { @class = "form-control" })
        <br/>*@
        <button class="btn btn-success">Update</button>

    </div>
}

MVC_Camp/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br /> 
<br /> 
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Category Name</th>
        <th>Delete</th>  
        <th>Update</th>  
        <th>Headers</th>  
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryId</th>
            <td>@item.CategoryName</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-danger">Delete</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryId" class="btn btn-warning">Update</a></td>
            <td><a href="#" class="btn btn-primary">Headings</a></td>
        </tr>
    }  
</table>

<a href="/AdminCategory/AddCategory" class="btn btn-info">New Category</a>

MVC_Camp/Views/Category/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h1>Add New Category Page</h1>
<br />
<p>Welcome aboard</p>

@using(Html.BeginForm("AddCategory", "Category", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Category Name:")
        @Html.TextBoxFor(x=>x.CategoryName)
        @Html.ValidationMessageFor(x=>x.CategoryName)
        <br /><br />
        @Html.Label("Enter the description:")
        @Html.TextBoxFor(x=>x.CategoryDescription)
        @Html.ValidationMessageFor(x=>x.CategoryDescription)
        <br /><br />
        <button>Save</button>
    </div>
}


@*<form class="form-group" method="post">
    <input class="form-control"  type="text" name="categoryName" value="" placeholder="Enter Category Name" />
    <br />
    <input class="form-control"  type="text" name="categoryDescription" value="" placeholder="Enter Category Description" />
    <br />
    <button class="btn btn-primary">Add</button> 
</form>*@

MVC_Camp/Views/Category/GetCategoryList.cshtml
@using EntityLayer.Concrete
@model List<Category>

@{
    Layout = null;
}

<!DOCTYPE html>

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h3>MVC Categories</h3>
<br />

<table class="table table-bordered ">
    <tr>
        <th>Category ID</th>
        <th>Category Name</th>
        <th>Category Description</th>
        <th>Category Status</th>
        <th>Update</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDescription</td>
            <td>@item.CategoryStatus</td>
            <td><button class="btn btn-info">Update</button></td>
        </tr>
    }
</table>

<a href="/Category/AddCategory" class="btn btn-info">New Category</a>

MVC_Camp/Views/Category/Index.cshtml
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h3>MVC Categories</h3>
<br />

<table class="table table-hover">
    <tr>
        <th>Category ID</th>
        <th>Category Name</th>
        <th>Category Description</th>
        <th>Category Status</th>
        <th>Update</th>  
    </tr>
    <tr>
        <td>1</td>
        <td>Education</td>
        <td>Education category</td>
        <td>true</td>
        <td><button class="btn btn-success">Update</button> </td>  
    </tr>

    <tr>
        <td>2</td>
        <td>Sport</td>
        <td>Sport category</td>
        <td>true</td>
        <td><button class="btn btn-success">Update</button> </td>  
    </tr>
    <tr>
        <td>3</td>
        <td>Book</td>
        <td>Book category</td>
        <td>true</td>
        <td><button class="btn btn-success">Update</button> </td>  
    </tr>

    <tr>
        <td>4</td>
        <td>Cinema</td>
        <td>Cinema category</td>
        <td>true</td>
        <td><button class="btn btn-success">Update</button> </td>  
    </tr>

</table>

<button class="btn btn-info">New Category</button>
<button class="btn btn-warning">Category List</button>
<button class="btn btn-danger">Category Description</button>

MVC_Camp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC_Camp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC_Camp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVC_Camp/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>AdminLTE 3 | Dashboard 3</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/AdminLTE-3.0.4/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/AdminLTE-3.0.4/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Categories
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Headings
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Writers
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Graphs
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Graph 1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Graph 2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Graph 3</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    About us
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Contacts & Messages
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Contents
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/calendar.html" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Authorizations
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/gallery.html" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Gallery
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Error Pages
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Enter the Site
                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-apple-alt"></i>
                                <p>
                                    Log out
                                </p>
                            </a>

                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.js"></script>
    <!-- OPTIONAL SCRIPTS -->
    <script src="~/AdminLTE-3.0.4/plugins/chart.js/Chart.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
</body>
</html>

MVC_Camp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC_Camp/Views/Statistics/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h2>Statistics Of Categories</h2>
<br />
<div class="row" style="margin-left: 10%">
    <div class="bg-gradient-red col-sm-2 card text-center" style="padding: 10px; margin-right: 10px">
        <div class="card-body">
            <h3 class="card-title" style="font-size: 20px">Number of Categories</h3>
            <p class="card-text" style="padding-top: 50px; font-size: 15px">@ViewBag.totalCategories</p>
        </div>
    </div>
    <div class="bg-gradient-primary col-sm-2 card text-center" style="padding: 10px; margin-right: 10px">
        <div class="card-body">
            <h1 class="card-title" style="font-size: 20px">Number of Headings in Development Category</h1>
            <p class="card-text" style="padding-top: 10px; font-size: 15px">@ViewBag.headingsInDevelopment</p>
        </div>
    </div>

    <div class="bg-gradient-gray-dark card col-sm-2 text-center" style="padding: 10px; margin-right: 10px ">
        <div class="card-body">
            <h1 class="card-title" style="font-size: 20px">Number of Writer that has 'a' in his or her name</h1>
            <p class="card-text" style="padding-top: 10px; font-size: 15px">@ViewBag.aInWriterName</p>
        </div>
    </div>
    <div class="bg-gradient-green card col-sm-2 text-center" style="padding: 10px; margin-right: 10px">
        <div class="card-body">
            <h1 class="card-title" style="font-size: 20px">Category Name That has more Headings Than Other</h1>
            <p class="card-text" style="padding-top: 10px; font-size: 15px">@ViewBag.mostHeadingsCategory</p>
        </div>
    </div>
    <div class="bg-gradient-info col-sm-2 card text-center" style="padding: 10px; margin-right: 10px">
        <div class="card-body">
            <h1 class="card-title" style="font-size: 20px">Number of Categories</h1>
            <p class="card-text" style="padding-top: 30px; font-size: 15px">@ViewBag.totalCategory</p>
            <p class="card-text" style="font-size: 15px">@ViewBag.messageForcategories</p>
        </div>
    </div>
</div>